Invoca/aggregate

aggregate.gemspec, lib/aggregate.rb, lib/aggregate/attribute/bitfield.rb, lib/aggregate/attribute_handler.rb, lib/aggregate/bitfield.rb, test/dummy/db/schema.rb, test/test_helper.rb, test/unit/attribute/bitfield_test.rb, test/unit/bitfield_test.rb, test/unit/combined_string_field_test.rb
Hey @c-simmons  - you touched it last so you win!
I have a project that is going to store 100 of booleans in an aggregate.  This was going to take about 2K when marshaled because of the JSON overhead.  Instead, I added a bitfield type which allows them to be stored in a single string attribute.  This is almost a 20x space savings!
Please let me know if you have any questions.
=> Define bitfield type

lib/aggregate/base.rb, test/unit/base_test.rb
@mikeweaver @codyjca please review 
For serialization we can use [`to_store`](https://github.com/Invoca/aggregate/blob/1e8ac42b534f6343f0e8267cb3e56aa0c5d02cd9/lib/aggregate/aggregate_store.rb#L66), so no change in the gem.
I added `from_json` method for deserialization, but I need to mention that we already had two methods:
The default initializer can take a hash as parameter but it will raise an exception if there is a key in the hash that does not exist as an attribute ([added a test for that](https://github.com/Invoca/aggregate/compare/98/t/STORY-3970_to_from_json?expand=1#diff-5293b6e4f7bca4190efe86a0f98c6046R33))
The second method is [`from_store`](https://github.com/Invoca/aggregate/blob/1e8ac42b534f6343f0e8267cb3e56aa0c5d02cd9/lib/aggregate/base.rb#L34) but this one will add the …
=> add from_json method and tests

Gemfile, aggregate.gemspec
@ColinDKelley - This update was generated by invoca_gem because of the version bump for large_text_field.
=> cdk/domain_name_and_region Update large_text_field to 0.0.2 (f83b33f)

Gemfile.lock, lib/aggregate/base.rb, lib/aggregate/version.rb, test/unit/base_test.rb
@mikeweaver @primiti @aschreifels 
Getting this code review up early so that I can get this into web to alleviate any issues around Aggregate classes instituting their own `to_hash` methods like DemographicResult does.
=> add as_json and to_hash methods to aggregate base

lib/aggregate/aggregate_store.rb, test/dummy/app/models/government_travel_itinerary.rb, test/dummy/db/migrate/20160316211434_create_travel_itineraries.rb, test/dummy/db/schema.rb, test/dummy/test/unit/government_travel_iternary_test.rb
@jacobdanielferguson - I ran into this issue when defining aggregates at different levels of the BulkOperation hierarchy.  Basically, when you define an aggregate to a derived class the aggregates defined in parent classes are not saved or loaded anymore.  The reason is that the class `@variable`  is overwritten and lost.   The fix was easy - when initializing the aggregate attributes for a class, check if the super class has them. If it does, dup them.
The rest is adding an STI test case to the dummy to prove this worked. 
Thanks
=> STORY-5105 - allow aggregates to work with Single Table Inheritance

Gemfile, Gemfile.lock, aggregate.gemspec, lib/aggregate.rb, lib/aggregate/engine.rb, test/dummy/config/routes.rb, test/test_helper.rb
- drop dependency on railties
- require railts
Without the explicit `require`, we're getting lucky that every time `aggregate` is pulled in _something_ pulled in `rails` first.
=> TECH-2930 require rails: fix dependencies

.gitignore, Gemfile.lock, lib/aggregate.rb, lib/aggregate/aggregate_store.rb, lib/aggregate/attribute/foreign_key.rb, lib/aggregate/attribute/hash.rb, lib/aggregate/foreign_key_reference.rb, test/dummy/app/models/flight.rb, test/dummy/app/models/passenger.rb, test/dummy/app/models/passport.rb, test/dummy/db/migrate/20180204000000_create_flights.rb, test/dummy/db/schema.rb, test/unit/aggregate_store_test.rb, test/unit/attribute/date_time_test.rb, test/unit/attribute/foreign_key_test.rb, test/unit/foreign_key_reference_test.rb
Alec and Omeed - This is a quick fix to not load the foreign key class when reading the id values from aggregate belongs_to fields.   
A future iteration will try to consolidate the queries so that we load all instances when we load the first.  But I want to hold off on that so we can get this out earlier.
=> TECH-3165 - belongs to should not auto-load when just returning the id

CHANGELOG.md, Gemfile.lock, README.md, lib/aggregate/container.rb, lib/aggregate/version.rb, test/dummy/app/models/flight.rb, test/dummy/app/models/passport.rb, test/dummy/app/models/travel_itinerary.rb, test/dummy/test/unit/government_travel_iternary_test.rb, test/dummy/test/unit/travel_itinerary_test.rb, test/unit/container_test.rb
This makes a minor interface change to large text field.   Remove the aggregate container options in favor of declarative methods that describe where the aggregate data can be saved.    All classes that include Aggregate::Container need to also call either `store_aggregates_using_large_text_field` or `store_aggregates_using :<my_storage_field>`.    The latter method takes an optional `migrate_from_storage_field:` argument that can be used to migrate storage from one field to another.  (This is what we use when we start removing large text field support form a model.)
We need to follow this pull request with a change to the definition of every aggregate to set the appropriate option.
=> TECH-2969 - allow aggregates to be defined without requiring large text field

CHANGELOG.md, lib/aggregate/attribute/base.rb, lib/aggregate/version.rb, test/unit/attribute/base_test.rb
Update `required` attribute option to only error out if `nil` is given. This is to allow supplying `false` for boolean fields.
=> STORY-6805 change history remove stub data

CHANGELOG.md, Gemfile.lock, lib/aggregate/attribute/hash.rb, lib/aggregate/version.rb, test/unit/attribute/hash_test.rb
* Update `store_hash_as_json` default to be true regardless of storage type
* This is so that elasticsearch models will by default store `hash` fields as JSON blobs without requiring `store_hash_as_json: true` to be set. This is to avoid inadvertently falling into the problem where a hash attribute creates an unnamed Elasticsearch document field which is untracked and may easily cause a field name collision.
=> no jira update hash json default

Gemfile, Gemfile.lock, aggregate.gemspec, lib/aggregate.rb
This is necessary to unblock our Gemfury conversion.
=> No jira relax hobo support dependency constraint

Gemfile.lock, aggregate.gemspec
These changes needed to unblock downstream consumers. 
This gem doesn't care what version of hobo_support is available, so long as version >= 2.0.0 is available.
=> No-Jira: relax hobo_support version

CHANGELOG.md, Gemfile.lock, lib/aggregate.rb, lib/aggregate/base.rb, lib/aggregate/container.rb, lib/aggregate/version.rb
- Fixed bug in Rails 5+ where `Aggregate::Base` and `Aggregate::Container` no longer had access to
callbacks defined by `ActiveRecord`
=> Tech 4591 rails 5 bundle install working

CHANGELOG.md, Gemfile.lock, lib/aggregate/aggregate_store.rb, lib/aggregate/container.rb, lib/aggregate/version.rb, test/unit/aggregate_store_test.rb, test/unit/container_test.rb
Correctly mark `#aggregate_attribute_changes` and `#changed?` when a value is changed from and back to its initial value.
Ensures that we're following Rails behavior with our "dirty" attribute methods
[Web PR](https://github.com/Invoca/web/pull/14408)
=> Web 5237 aggregate attribute changes

CHANGELOG.md, Gemfile.lock, lib/aggregate/aggregate_store.rb, lib/aggregate/container.rb, lib/aggregate/version.rb, test/unit/aggregate_store_test.rb
- Add before save functionality
- Allows saved change methods to be called even when save is in progress.
- `#saved_changes?`
- `#aggregate_attribute_saved_changes`
- `#saved_change_to_{attribute}?`
Note: I tested this against web and was able to get the rails 5 tests green for `test/models/change_history/observers/*test.rb`!
=> Tech 5525 before save for saved changes

CHANGELOG.md, Gemfile.lock, lib/aggregate/aggregate_store.rb, lib/aggregate/version.rb, test/unit/aggregate_store_test.rb
WEB PR: https://github.com/Invoca/web/pull/15152
[TECH-5306](https://ringrevenue.atlassian.net/browse/TECH-5306)
From the README updates:
> - Fixed an issue for Rails 5 where autosave associations weren't being recognized to be saved when the only changes on the object are aggregate attributes.
>   - This was primarily an issue with objects that utilize storing their aggregate data via LargeTextField and trying to have that object be autosaved by saving the object's parent relationship object.
> 
> E.g.
> ```ruby
> advertiser_campaign.future_terms.build_commission_budget_terms({...})
> advertiser_campaign.save! # This would not save the commission budget terms aggregate attribute on the future campaign terms
> ```
Main change is overriding …
=> TECH-5306 rails5 changed for autosave fix

CHANGELOG.md, Gemfile.lock, lib/aggregate/bitfield.rb, lib/aggregate/version.rb, test/dummy/test/unit/passport_test.rb, test/unit/bitfield_test.rb
Currently, empty bitfields are writing null values to the JSON storage. 
For example:
```{\"stamps\":null}```
=> no-jira: fix bitfield storage bug, add empty? method to bitfield

README.md
Update README.md to add warning about using `before_save` that changes any aggregate attributes
Not bumping the gem version because this is only a `README` change.
=> non production update readme before save warning: Update README.md to add warning about using before_save that changes any aggregate attributes

CHANGELOG.md, Gemfile, Gemfile.lock, aggregate.gemspec, gemfiles/activerecord_6_0.gemfile, gemfiles/activerecord_6_1.gemfile, gemfiles/activerecord_7_0.gemfile, gemfiles/activerecord_7_1.gemfile, gemfiles/rails_5.gemfile, gemfiles/rails_6.gemfile, lib/aggregate/aggregate_store.rb, lib/aggregate/attribute/boolean.rb, lib/aggregate/base.rb, lib/aggregate/combined_string_field.rb, lib/aggregate/container.rb, lib/aggregate/version.rb, test/aggregate_test.rb, test/dummy/config.ru, test/dummy/config/initializers/backtrace_silencers.rb, test/dummy/config/initializers/inflections.rb, test/dummy/config/initializers/mime_types.rb, test/dummy/test/unit/passport_test.rb, test/unit/aggregate_store_test.rb, test/unit/attribute/list_test.rb, test/unit/bitfield_test.rb, test/unit/combined_string_field_test.rb, test/unit/container_test.rb
This was causing issues on shoulda-matchers version 4, where because this method was defined, it thought we were an ActiveRecord model and had access to `columns` method. This change now fixes the problem on Rails 7.1 but also fixes the issue we're seeing on shoulda 4
=> fix numericality validation to skip db checking

CHANGELOG.md, Gemfile.lock, lib/aggregate/base.rb, lib/aggregate/version.rb, test/unit/base_test.rb, test/unit/container_test.rb
Rails allows two ways to define a numericality validation on a model.
This change ensures we can handle both cases
=> fix numericality validation

CHANGELOG.md, Gemfile.lock, lib/aggregate/base.rb, lib/aggregate/version.rb
Adds includes `ActiveModel::Validations` in `Aggregate::Base` to fix an error when running rails 7.2.
Aggregate::Base has the following includes:
```
include ActiveRecord::Validations
include ActiveRecord::Callbacks
```
In rails 7.1, ActiveRecord::Validations [used to include](https://github.com/rails/rails/blob/7-1-stable/activerecord/lib/active_record/validations.rb#L42) ActiveModel::Validations, which is where the validate method comes from. That include statement is no longer present in 7.2. `ActiveModel::Validations` needs to be included directly now to make use of the `validate` method.
=> WEB-7877: include ActiveModel::Validations in Aggregate::Base
